name: Build and deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Chekout Repository
        uses: actions/checkout@main
      - name: NodeJS
        uses: actions/setup-node@main
        with:
          node-version: 10.x
      - name: Install dependencies
        run: npm ci
        working-directory: react
      - name: Build dependencies
        run: npm run build
        working-directory: ./react
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: node-build
          path: ./react
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: node-build
          path: .
      - name: Sync files to remote server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: szoftarch.webgravir.hu
          username: github@szoftarch.webgravir.hu
          password: ${{ secrets.FTP_PASS }}
